development:
   adapter: mysql2
   encoding: utf8
   database: emp_dev
   username: root
   password: root
   host: localhost
  
test:
   adapter: mysql2
   encoding: utf8
   database: emp_test
   username: root
   password: root
   host: localhost
   
# production:
#    adapter: mysql
#    database: library_production
#    username: root
#    password: root
#    host: localhost
